{
 "title": "Power Supervision",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "device_id",
    "query": {
     "query": "label_values(module_device_info, device)"
    }
   },
   {
    "name": "names",
    "query": {
     "query": "label_values(module_device_info, name)"
    }
   },
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "label_values(module_device_info{tag=~\"$tags\", type=~\"$type\"}, name)"
    }
   },
   {
    "name": "device_name",
    "query": {
     "query": "label_values(module_device_info{device=\"$device_id\"}, name)"
    }
   },
   {
    "name": "tags",
    "label": "Pièce",
    "query": {
     "query": "label_values(module_device_info, tag)"
    }
   },
   {
    "name": "type",
    "label": "Type",
    "query": {
     "query": "label_values(module_device_info, type)"
    }
   },
   { "name": "kwh_price", "query": "${VAR_KWH_PRICE}" },
   { "name": "subscription_price", "query": "${VAR_SUBSCRIPTION_PRICE}" },
   { "name": "kwh", "query": "${VAR_KWH}" }
  ]
 },
 "panels": [
  {
   "title": "Résumé",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Conso instantannée",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(module_power_consumption{name=~\"$device\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Coût journalier",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(module_power_consumption{name=~\"$device\"})*0.001*24*$kwh_price",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total mensuel",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(module_power_consumption{name=~\"$device\"}[30d])*0.001*24*30.5*$kwh_price)+$subscription_price",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Température",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "room_temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "room_humidity", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Résumé",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "module_power_consumption{name=~\"$device\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "module_power_status{name=~\"$device\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(module_power_consumption{name=~\"$device\"}[30d])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "avg_over_time(module_power_consumption{name=~\"$device\"}[$__range])-avg_over_time(module_power_consumption{name=~\"$device\"}[30d])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "avg_over_time(module_power_consumption{name=~\"$device\"}[30d])*0.001*24*30.5*$kwh_price",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Historique", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Par appareil",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum (module_power_consumption{tag=~\"$tags\", name=~\"$device\", type=~\"$type\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Totale",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum (module_power_consumption{tag=~\"$tags\", name=~\"$device\", type=~\"$type\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Par pièce",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum (module_power_consumption{tag=~\"$tags\", name=~\"$device\", type=~\"$type\"}) by (tag)",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "Par type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum (module_power_consumption{tag=~\"$tags\", name=~\"$device\", type=~\"$type\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Répartitions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Par appareil",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 2, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(module_power_consumption{tag=~\"$tags\", name=~\"$device\", type=~\"$type\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Par pièce",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 9, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(module_power_consumption{tag=~\"$tags\", name=~\"$device\", type=~\"$type\"}) by (tag))by (tag)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Par type",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(module_power_consumption{tag=~\"$tags\", name=~\"$device\", type=~\"$type\"}) by (type)) by(type)",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}