{
 "title": "GeoRide Tracker",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "tracker_id",
    "label": "Tracker",
    "query": {
     "query": "label_values(tracker_metadata{device_name=\"$trackers_name\"},device_id)"
    }
   },
   {
    "name": "trackers_name",
    "label": "Moto",
    "query": {
     "query": "label_values(tracker_metadata,device_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Metadata", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "expr": "tracker_metadata" }
   ]
  },
  {
   "title": "Tracker version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tracker_status_updated", "legendFormat": "{{device_name}}" }
   ]
  },
  {
   "title": "eCall",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tracker_feature_ecall", "legendFormat": "{{device_name}}" }
   ]
  },
  {
   "title": "Theft assistance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tracker_feature_assistancetheft",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Crash detection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tracker_feature_crashdetection", "legendFormat": "{{device_name}}" }
   ]
  },
  {
   "title": "Mileage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bicycle_odometer", "legendFormat": "{{device_name}}" }
   ]
  },
  { "title": "Batteries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Tracker battery",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "tracker_battery_voltage", "legendFormat": "{{device_name}}" }
   ]
  },
  {
   "title": "Bicycle battery",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "bicycle_battery_voltage", "legendFormat": "{{device_name}}" }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Tracker Online",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "tracker_status_online", "legendFormat": "{{device_name}}" }
   ]
  },
  {
   "title": "Motorcycle Running",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "tracker_status_electric_mode", "legendFormat": "{{device_name}}" }
   ]
  },
  {
   "title": "Tracker eco mode",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 20 },
   "targets": [
    { "expr": "tracker_status_eco_mode", "legendFormat": "{{device_name}}" }
   ]
  },
  {
   "title": "Motorcycle Moving",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 20 },
   "targets": [
    { "expr": "bicycle_moving", "legendFormat": "{{device_name}}" }
   ]
  },
  {
   "title": "Tracker locked",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "tracker_status_locked", "legendFormat": "{{device_name}}" }
   ]
  },
  {
   "title": "Motorcycle Crashed",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "tracker_status_crashed", "legendFormat": "{{device_name}}" }
   ]
  },
  {
   "title": "Motorcycle Stolen",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 28 },
   "targets": [
    { "expr": "tracker_status_stolen", "legendFormat": "{{device_name}}" }
   ]
  },
  { "title": "Location / Speed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Locations",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "targets": [
    { "expr": "bicycle_latitude", "legendFormat": "__auto" },
    { "expr": "bicycle_longitude", "legendFormat": "__auto" },
    { "expr": "tracker_locked_latitude", "legendFormat": "__auto" },
    { "expr": "tracker_locked_longitude", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    { "expr": "bicycle_speed*1.852", "legendFormat": "{{device_name}}" }
   ]
  }
 ]
}