{
 "title": "Palworld Server",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Player status",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "player_status{name!~\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"192.168.0.212:9100\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"192.168.0.212:9100\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"192.168.0.212:9100\"}) by (cpu))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.0.212:9100\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.0.212:9100\"} - node_memory_MemFree_bytes{instance=\"192.168.0.212:9100\"} - (node_memory_Cached_bytes{instance=\"192.168.0.212:9100\"} + node_memory_Buffers_bytes{instance=\"192.168.0.212:9100\"})",
     "legendFormat": "RAM Usage"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"192.168.0.212:9100\",device!=\"lo\"}[5m])",
     "legendFormat": "Download"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"192.168.0.212:9100\",device!=\"lo\"}[5m])",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"192.168.0.212:9100\",device=~\"^/dev/mapper.*\"}",
     "legendFormat": "FS Size"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"192.168.0.212:9100\",device=~\"^/dev/mapper.*\"} - node_filesystem_avail_bytes{instance=\"192.168.0.212:9100\",device=~\"^/dev/mapper.*\"}",
     "legendFormat": "FS Used"
    }
   ]
  }
 ]
}