{
 "title": "Plex Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 14, "x": 1, "y": 1 },
   "options": {
    "content": "<br>\r\n<br>\r\n<center>\r\n    <h1 style=\"font-size:75px; color:#E5A00D\">\r\n        Ebenolt-Stream\r\n    </h1>\r\n</center>"
   },
   "targets": [
    { "expr": "plex_server_info" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Films" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "plex_library_section_size_count{name=\"Films\", server_name=\"Ebenolt-Stream\"}"
    }
   ]
  },
  {
   "title": "Streams Actifs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "plex_sessions_active_count{server_name=\"Ebenolt-Stream\"}",
     "legendFormat": "Streams Actifs"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"192.168.0.206:9100\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"192.168.0.206:9100\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"192.168.0.206:9100\"}) by (cpu))",
     "legendFormat": "% CPU"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"192.168.0.206:9100\"} * 100) / node_memory_MemTotal_bytes{instance=\"192.168.0.206:9100\"})",
     "legendFormat": "% RAM"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "module_power_consumption{name=\"Serveurs\"}",
     "legendFormat": "Power draw"
    }
   ]
  }
 ]
}