{
 "title": "NAS Monitor",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"nas_monitor\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',job=\"nas_monitor\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{job=\"nas_monitor\"}) by (cpu))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_thermal_zone_temp", "legendFormat": "RAM" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds-node_boot_time_seconds{job=\"nas_monitor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "(1 - (node_memory_Cached_bytes{job=\"nas_monitor\"} + node_memory_MemFree_bytes ) / node_memory_MemTotal_bytes{job=\"nas_monitor\"}) * 100",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"nas_monitor\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',job=\"nas_monitor\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{job=\"nas_monitor\"}) by (cpu))",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_Cached_bytes{job=\"nas_monitor\"} + node_memory_MemFree_bytes ) / node_memory_MemTotal_bytes{job=\"nas_monitor\"}) * 100",
     "legendFormat": "RAM"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Espace utilisé",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"nas_monitor\",mountpoint=~\"/share/CACHEDEV.*\", fstype=\"ext4\"} - node_filesystem_free_bytes{job=\"nas_monitor\",mountpoint=~\"/share/CACHEDEV.*\", fstype=\"ext4\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Espace Total",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"nas_monitor\",mountpoint=~\"/share/CACHEDEV.*\", fstype=\"ext4\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Espace restant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{job=\"nas_monitor\",mountpoint=~\"/share/CACHEDEV.*\", fstype=\"ext4\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Utilisation des disques",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=\"nas_monitor\", device=\"dm-4\"}[5m])",
     "legendFormat": "Lecture"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{job=\"nas_monitor\", device=\"dm-4\"}[5m])",
     "legendFormat": "Ecriture"
    }
   ]
  },
  {
   "title": "Utilisation Réseau",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_netstat_IpExt_InOctets{job=\"nas_monitor\"}[5m])",
     "legendFormat": "Upload to NAS"
    },
    {
     "expr": "rate(node_netstat_IpExt_OutOctets{job=\"nas_monitor\"}[5m])",
     "legendFormat": "Download from NAS"
    }
   ]
  },
  {
   "title": "Nombre de fichiers (en millions)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_filesystem_files{job=\"nas_monitor\",mountpoint=~\"/share/CACHEDEV.*\", fstype=\"ext4\"} / 1000000",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}