{
 "title": "VCSA Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cpu_freq",
    "query": {
     "query": "query_result(vmware_host_cpu_max/vmware_host_num_cpu*1000000)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - vmware_host_boot_timestamp_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Templates",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(time() - vmware_vm_boot_timestamp_seconds{ds_name=~\".*Templates.*\"}) by (vm_name) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(vmware_vm_memory_max) by (vm_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(vmware_vm_num_cpu{ds_name=~\".*Templates.*\"}) by (vm_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Datastores",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "vmware_datastore_capacity_size", "legendFormat": "__auto" },
    { "expr": "vmware_datastore_vms", "legendFormat": "__auto" },
    {
     "expr": "vmware_datastore_freespace_size",
     "legendFormat": "__auto"
    },
    {
     "expr": "vmware_datastore_provisoned_size",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 1, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vmware_host_num_cpu", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vmware_host_memory_max", "legendFormat": "__auto" }
   ]
  },
  { "title": "Guest - Infos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Infos",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(vmware_vm_guest_tools_running_status{ds_name!~\".*Templates.*\"}) by (vm_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(time() - vmware_vm_boot_timestamp_seconds{ds_name!~\".*Templates.*\"}) by (vm_name) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(vmware_vm_memory_max) by (vm_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(vmware_vm_num_cpu{ds_name!~\".*Templates.*\"}) by (vm_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(vmware_vm_guest_disk_capacity{ds_name!~\".*Templates.*\"}) by (vm_name) * 0.79",
     "legendFormat": "__auto"
    },
    { "expr": "vmware_vm_power_state", "legendFormat": "__auto" }
   ]
  },
  { "title": "Guest - CPU / RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "VM Active Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "sum(vmware_vm_mem_active_average) by (vm_name)",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "VM Active CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "sum(vmware_vm_cpu_usagemhz_average) by (vm_name) * 1000000",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Guest - Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Free",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(vmware_vm_guest_disk_free) by (vm_name) * 0.79",
       "legendFormat": "{{vm_name}}"
      }
     ]
    },
    {
     "title": "Disk Usage (Read)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "KiBs" } },
     "targets": [
      {
       "expr": "sum(vmware_vm_disk_read_average) by (vm_name)",
       "legendFormat": "Read - {{vm_name}}"
      }
     ]
    },
    {
     "title": "Disk Usage (Write)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "KiBs" } },
     "targets": [
      {
       "expr": "sum(vmware_vm_disk_write_average) by (vm_name)",
       "legendFormat": "{{vm_name}}"
      }
     ]
    }
   ]
  },
  { "title": "Datastores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "DS Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "vmware_datastore_provisoned_size",
     "legendFormat": "{{ds_name}}"
    }
   ]
  },
  {
   "title": "DS Free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "vmware_datastore_freespace_size",
     "legendFormat": "{{ds_name}}"
    }
   ]
  },
  {
   "title": "To be tested",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Usage",
     "type": "timeseries",
     "description": "vmware_vm_net_transmitted_average\nvmware_vm_net_received_average",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(vmware_vm_net_transmitted_average) by (vm_name)",
       "legendFormat": "{{vm_name}}"
      }
     ]
    }
   ]
  }
 ]
}